"""Formatted Word export (reversa.docx_export)."""
import re
import zipfile
from pathlib import Path

import pytest

pytest.importorskip("pypandoc")

from reversa.docx_export import build_docx, ordered_markdown_files  # noqa: E402

W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"


def _paragraphs(path: Path) -> list[tuple[str, str]]:
    """(style id, text) for every body paragraph."""
    import xml.etree.ElementTree as ET
    with zipfile.ZipFile(path) as z:
        root = ET.fromstring(z.read("word/document.xml"))
    out = []
    for p in root.iter(W + "p"):
        st = p.find(f"{W}pPr/{W}pStyle")
        out.append((st.get(W + "val") if st is not None else "", "".join(t.text or "" for t in p.iter(W + "t"))))
    return out

LONG = "The output record is written using the fee amount, but the fee amount is not calculated " * 4


def _sdd(tmp_path: Path) -> Path:
    sdd = tmp_path / "_reversa_sdd"
    (sdd / "specs" / "pay").mkdir(parents=True)
    (sdd / "README.md").write_text(
        "# Reversa operational specification\n\n"
        "Generated by Reversa for `src` (backend: hybrid-qwen).\n\n"
        "**Read this first:** Internal confidence index: 81.1% over 66 claims — a summary.\n\n"
        "Units: PAYFEE01\n")
    (sdd / "ops_spec.md").write_text(
        "# Detailed operational specification\n\n## PAYFEE01\n\n### Level 3 — Flow\n\n"
        "1. Start step \"0000 main\".\n2. Open the files.\n\n"
        "### Level 4 — Rules\n\n**BR-01 · Decision** — ✅ Confirmed  \nThe rule text.  \n"
        "_Source:_ `PAYFEE01.cbl:46`\n\n"
        "### Level 6 — Gaps\n\n| ID | Type | Severity | Finding | Question | Lines |\n|---|---|---|---|---|---|\n"
        f"| GC-01 | Value | High | {LONG} | Should it be? | 65 |\n")
    (sdd / "process_flow.md").write_text(
        "# Process\n\n## PAYFEE01\n\n1. Start step.\n2. Next step.\n\n"
        "| # | Unit | Step | If true | If false | Evidence |\n|---|---|---|---|---|---|\n\n"
        "<details><summary>Technical detail</summary>\n\n- **BR-01** `X` — a:1\n\n</details>\n")
    (sdd / "comparison.md").write_text(
        "# Standards comparison\n\n## Checked\n\n| A | B | C | D | E | F | G |\n|---|---|---|---|---|---|---|\n"
        "| 1 | 2 | 3 | 4 | 5 | 6 | 7 |\n")
    (sdd / "specs" / "pay" / "tasks.md").write_text("- T-1 do it\n")          # no heading
    return sdd


def test_order_follows_reading_order(tmp_path):
    sdd = _sdd(tmp_path)
    names = [p.relative_to(sdd).as_posix() for p in ordered_markdown_files(sdd)]
    assert names[:3] == ["README.md", "ops_spec.md", "process_flow.md"]


def test_structure(tmp_path):
    sdd = _sdd(tmp_path)
    out = build_docx(sdd, tmp_path / "spec.docx", title="Operational Specification", paginate="off")
    paras = _paragraphs(out)
    heads = [t for st, t in paras if st.startswith("Heading")]
    # file names replaced by numbered sections; renamed titles; synthesized title for a heading-less file
    assert heads[0] == "1\u2003About this document"
    assert "3\u2003Process flow" in heads
    assert any(h.endswith("Specs \u203a pay \u203a tasks") for h in heads)
    assert "2.1.1\u2003Level 3 \u2014 Flow" in heads
    # title page carries facts harvested from the artifacts
    body = "\n".join(t for _, t in paras[:12])
    assert "Operational Specification" in body and "PAYFEE01" in body
    assert "hybrid-qwen backend" in body and "81.1% over 66 claims" in body
    with zipfile.ZipFile(out) as z:
        xml = z.read("word/document.xml").decode()
        footers = "".join(z.read(n).decode() for n in z.namelist() if n.startswith("word/footer"))
        settings = z.read("word/settings.xml").decode()
        fonts = set(re.findall(r'w:ascii="([^"]+)"', "".join(
            z.read(n).decode() for n in z.namelist() if n.endswith(".xml"))))
    # contents is a real TOC field; footer has page fields; Word refreshes fields on open
    assert 'TOC \\o "1-2"' in xml and 'w:anchor="_Toc0001"' in xml
    assert "PAGE" in footers and "NUMPAGES" in footers
    assert "w:updateFields" in settings
    # only fonts every Mac and PC has (Pages warns about anything else)
    assert fonts <= {"Arial", "Courier New"}, fonts
    # empty table -> note; long-text table -> card (not a table); details summary kept
    texts = [t for _, t in paras]
    assert "None recorded." in texts and "Technical detail" in texts
    assert any(t.startswith("GC-01") and "Severity: High" in t for t in texts)
    # the 7-column table sits in a landscape section; the document starts portrait
    orients = re.findall(r'<w:pgSz w:w="(\d+)" w:h="(\d+)"', xml)
    assert orients[0][0] < orients[0][1] and any(int(w) > int(h) for w, h in orients)
    assert xml.count("<w:tbl>") == 1


def test_on_pipeline_output(atm: Path):
    from reversa.llm import get_backend
    from reversa.orchestrator import Orchestrator
    Orchestrator(atm, get_backend("heuristic"), log=lambda *a, **k: None).run(team="discovery")
    out = build_docx(atm / "_reversa_sdd", atm / "spec.docx", paginate="off")
    assert sum(st == "Heading1" for st, _ in _paragraphs(out)) >= 5
