"""reversa-writer: convert extracted knowledge into unit-level specifications.

Outputs per unit (paper Table 2): requirements.md, design.md, tasks.md, plus
traceability/code-spec-matrix.md across units. Every requirement lists the
claim ids it is derived from, so spec -> claim -> code is always navigable.
The Writer "omits lines when there is not enough basis" (§3.5): requirements
are only generated from confirmed or inferred claims; gaps become open items.
"""
from __future__ import annotations

from collections import defaultdict
from typing import Any

from ..models import Claim, ClaimKind, Confidence
from .base import Agent, Context

_REQ_KINDS = (ClaimKind.BEHAVIOR, ClaimKind.RULE, ClaimKind.STATE, ClaimKind.PERMISSION, ClaimKind.EXCEPTION)
_DESIGN_KINDS = (ClaimKind.STRUCTURE, ClaimKind.DATA, ClaimKind.DEPENDENCY, ClaimKind.ARCHITECTURE)


class Writer(Agent):
    name = "reversa-writer"
    role = ("Write the operational specification of one unit for a coding agent: "
            "requirements (behaviours to preserve), design (structure, data, "
            "dependencies) and reimplementation tasks. Every requirement must list the "
            "claim ids it derives from. Keep the confidence marking of the underlying "
            "claims; do not upgrade an inferred claim by writing it assertively. If a "
            "requirement would rest only on gaps, leave it out and reference the gap.")
    output_schema = {
        "purpose": "<one paragraph: what the unit is for>",
        "requirements": [{"id": "REQ-1", "text": "The system shall ...", "claims": ["C-001"],
                          "confidence": "confirmed|inferred"}],
        "design": {"structure": "<paragraph>", "data": "<paragraph>", "dependencies": "<paragraph>",
                   "claims": ["C-002"]},
        "tasks": [{"id": "T-1", "title": "...", "description": "...", "requirements": ["REQ-1"],
                   "depends_on": []}],
    }

    def user_prompt(self, payload: dict[str, Any]) -> str:
        cl = "\n".join(f"- [{c['id']}] ({c['kind']}, {c['confidence']}) {c['statement']}"
                       for c in payload["claims"])
        gaps = "\n".join(f"- [{g['id']}] {g['description']}" for g in payload["gaps"]) or "- (none)"
        return (f"Unit: {payload['unit']}\n\nClaims:\n{cl}\n\nOpen gaps:\n{gaps}\n\n"
                "Write requirements, design and tasks. Requirements must reference claim ids.")

    def heuristic(self, payload: dict[str, Any]) -> dict[str, Any]:
        unit = payload["unit"]
        claims = [c for c in payload["claims"] if c["confidence"] != "gap"]
        reqs, n = [], 0
        for c in claims:
            if c["kind"] in {k.value for k in _REQ_KINDS}:
                n += 1
                verb = "shall" if c["confidence"] == "confirmed" else "should (to be confirmed)"
                reqs.append({"id": f"REQ-{n}", "text": f"The reimplementation {verb} preserve: {c['statement']}",
                             "claims": [c["id"]], "confidence": c["confidence"]})
        design_claims = [c for c in claims if c["kind"] in {k.value for k in _DESIGN_KINDS}]
        by = defaultdict(list)
        for c in design_claims:
            by[c["kind"]].append(c["statement"])
        design = {
            "structure": " ".join(by.get("structure", [])) or "Structure not recovered.",
            "data": " ".join(by.get("data", [])) or "No persistent data recovered.",
            "dependencies": " ".join(by.get("dependency", []) + by.get("architecture", [])) or "No dependencies recovered.",
            "claims": [c["id"] for c in design_claims],
        }
        tasks = [{"id": "T-1", "title": f"Scaffold {unit}", "description": f"Create the target-language module for {unit} "
                  f"with the structure and data described in design.md.", "requirements": [], "depends_on": []}]
        groups = defaultdict(list)
        for r, c in zip(reqs, [c for c in claims if c["kind"] in {k.value for k in _REQ_KINDS}]):
            groups[c["kind"]].append(r["id"])
        i = 1
        for kind, rids in groups.items():
            i += 1
            tasks.append({"id": f"T-{i}", "title": f"Implement {kind} requirements of {unit}",
                          "description": f"Implement {', '.join(rids)} and cover each with a parity test.",
                          "requirements": rids, "depends_on": ["T-1"]})
        tasks.append({"id": f"T-{i + 1}", "title": f"Parity tests for {unit}",
                      "description": "Run the Gherkin parity scenarios generated by the migration team against "
                                     "both legacy and target; resolve open gaps before cutover.",
                      "requirements": [r["id"] for r in reqs], "depends_on": [t["id"] for t in tasks[1:]]})
        purpose = (f"{unit} — purpose reconstructed from {len(claims)} claims "
                   f"({sum(1 for c in claims if c['confidence']=='confirmed')} confirmed, "
                   f"{sum(1 for c in claims if c['confidence']=='inferred')} inferred).")
        return {"purpose": purpose, "requirements": reqs, "design": design, "tasks": tasks}

    def run(self, ctx: Context) -> None:
        reg = ctx.registry
        matrix: list[tuple[str, str, str, str]] = []  # (file:lines, claim, unit, req)
        specs: dict[str, dict[str, Any]] = {}
        for u in ctx.selected_units():
            claims = reg.claims_for(u.name)
            gaps = [g for g in reg.gaps if g.unit == u.name]
            payload = {"unit": u.name, "claims": [c.to_dict() for c in claims],
                       "gaps": [g.to_dict() for g in gaps]}
            out = ctx.backend.generate(self, payload)
            self.record_warnings(ctx, out, u.name)
            # enforce: requirements may only cite existing claims of this unit
            valid = {c.id: c for c in claims}
            reqs = []
            for r in out.get("requirements", []):
                cids = [cid for cid in r.get("claims", []) if cid in valid]
                if not cids:
                    continue
                confs = {valid[c].confidence for c in cids}
                conf = "confirmed" if confs == {Confidence.CONFIRMED} else "inferred"
                reqs.append({"id": r["id"], "text": r["text"], "claims": cids, "confidence": conf})
            out["requirements"] = reqs
            specs[u.name] = out
            self._write_unit(ctx, u.name, out, valid, gaps)
            for r in reqs:
                for cid in r["claims"]:
                    for e in valid[cid].evidence:
                        matrix.append((e.ref(), cid, u.name, r["id"]))
            ctx.log(f"  writer: {u.name}: {len(reqs)} requirements, {len(out.get('tasks', []))} tasks")
        reg.meta["specs"] = {k: {"requirements": v["requirements"], "tasks": v.get("tasks", [])}
                             for k, v in specs.items()}
        rows = "\n".join(f"| `{f}` | {c} | {u} | {r} |" for f, c, u, r in sorted(set(matrix))) or "| — | — | — | — |"
        ctx.write("traceability/code-spec-matrix.md", f"""# Code → spec traceability matrix

Each row links a code location to the claim it supports and the requirement that claim feeds.

| Code | Claim | Unit | Requirement |
|---|---|---|---|
{rows}
""")

    def _write_unit(self, ctx: Context, unit: str, out: dict[str, Any], valid: dict[str, Claim], gaps) -> None:
        tag = lambda c: {"confirmed": "✅", "inferred": "🟡"}.get(c, "⛔")
        req_lines = []
        for r in out["requirements"]:
            refs = "; ".join(e.ref() for cid in r["claims"] for e in valid[cid].evidence) or "no direct evidence"
            req_lines.append(f"- {tag(r['confidence'])} **{r['id']}** {r['text']}  \n"
                             f"  _claims: {', '.join(r['claims'])} · evidence: {refs}_")
        gap_lines = [f"- ⛔ **{g.id}** ({g.severity.value}{', blocking' if g.blocking else ''}) {g.description}"
                     for g in gaps if g.status == "open"]
        d = out.get("design", {}) or {}
        ctx.write(f"specs/{unit.lower()}/requirements.md", f"""# Requirements — {unit}

{out.get('purpose', '')}

## Behaviours to preserve

{chr(10).join(req_lines) or '- (no requirement could be derived from evidence)'}

## Open gaps affecting this unit

{chr(10).join(gap_lines) or '- (none)'}

Legend: ✅ confirmed · 🟡 inferred (validate before relying on it) · ⛔ gap
""")
        ctx.write(f"specs/{unit.lower()}/design.md", f"""# Design — {unit}

## Structure
{d.get('structure', '')}

## Data
{d.get('data', '')}

## Dependencies
{d.get('dependencies', '')}

_Derived from claims: {', '.join(d.get('claims', [])) or '—'}_
""")
        t_lines = []
        for t in out.get("tasks", []):
            dep = f" (after {', '.join(t['depends_on'])})" if t.get("depends_on") else ""
            t_lines.append(f"- [ ] **{t['id']}** {t['title']}{dep}  \n  {t.get('description', '')}  \n"
                           f"  _requirements: {', '.join(t.get('requirements', [])) or '—'}_")
        ctx.write(f"specs/{unit.lower()}/tasks.md", f"""# Tasks — {unit}

{chr(10).join(t_lines) or '- (none)'}
""")
